"""Generated from FiscalRail's OpenAPI contract. Do not edit by hand."""

from dataclasses import dataclass
from typing import Final

CONTRACT_VERSION: Final = "1.0.0"


@dataclass(frozen=True, slots=True)
class Operation:
    method: str
    path: str
    tag: str | None
    request_model: str | None
    response_model: str | None
    success_statuses: tuple[int, ...]


OPERATIONS: Final[dict[str, Operation]] = {
    "listAccounts": Operation(
        method="GET",
        path="/accounts",
        tag="Accounts",
        request_model=None,
        response_model="AccountList",
        success_statuses=(200,),
    ),
    "retrieveAccount": Operation(
        method="GET",
        path="/accounts/{id}",
        tag="Accounts",
        request_model=None,
        response_model="Account",
        success_statuses=(200,),
    ),
    "updateAccount": Operation(
        method="PATCH",
        path="/accounts/{id}",
        tag="Accounts",
        request_model="AccountUpdate",
        response_model="Account",
        success_statuses=(200,),
    ),
    "listApiKeys": Operation(
        method="GET",
        path="/api-keys",
        tag="API keys",
        request_model=None,
        response_model="ApiKeyList",
        success_statuses=(200,),
    ),
    "createApiKey": Operation(
        method="POST",
        path="/api-keys",
        tag="API keys",
        request_model="ApiKeyCreate",
        response_model="ApiKey",
        success_statuses=(201,),
    ),
    "retrieveApiKey": Operation(
        method="GET",
        path="/api-keys/{id}",
        tag="API keys",
        request_model=None,
        response_model="ApiKey",
        success_statuses=(200,),
    ),
    "deleteApiKey": Operation(
        method="DELETE",
        path="/api-keys/{id}",
        tag="API keys",
        request_model=None,
        response_model=None,
        success_statuses=(204,),
    ),
    "listEvents": Operation(
        method="GET",
        path="/events",
        tag="Events",
        request_model=None,
        response_model="EventList",
        success_statuses=(200,),
    ),
    "retrieveEvent": Operation(
        method="GET",
        path="/events/{id}",
        tag="Events",
        request_model=None,
        response_model="Event",
        success_statuses=(200,),
    ),
    "listEventDestinations": Operation(
        method="GET",
        path="/event-destinations",
        tag="Event destinations",
        request_model=None,
        response_model="EventDestinationList",
        success_statuses=(200,),
    ),
    "createEventDestination": Operation(
        method="POST",
        path="/event-destinations",
        tag="Event destinations",
        request_model="EventDestinationCreate",
        response_model="EventDestination",
        success_statuses=(201,),
    ),
    "retrieveEventDestination": Operation(
        method="GET",
        path="/event-destinations/{id}",
        tag="Event destinations",
        request_model=None,
        response_model="EventDestination",
        success_statuses=(200,),
    ),
    "updateEventDestination": Operation(
        method="PATCH",
        path="/event-destinations/{id}",
        tag="Event destinations",
        request_model="EventDestinationUpdate",
        response_model="EventDestination",
        success_statuses=(200,),
    ),
    "deleteEventDestination": Operation(
        method="DELETE",
        path="/event-destinations/{id}",
        tag="Event destinations",
        request_model=None,
        response_model=None,
        success_statuses=(204,),
    ),
    "enableEventDestination": Operation(
        method="POST",
        path="/event-destinations/{id}/enable",
        tag="Event destinations",
        request_model=None,
        response_model="EventDestination",
        success_statuses=(200,),
    ),
    "disableEventDestination": Operation(
        method="POST",
        path="/event-destinations/{id}/disable",
        tag="Event destinations",
        request_model=None,
        response_model="EventDestination",
        success_statuses=(200,),
    ),
    "listInvoiceSeries": Operation(
        method="GET",
        path="/invoice-series",
        tag="Invoice series",
        request_model=None,
        response_model="InvoiceSeriesList",
        success_statuses=(200,),
    ),
    "createInvoiceSeries": Operation(
        method="POST",
        path="/invoice-series",
        tag="Invoice series",
        request_model="InvoiceSeriesCreate",
        response_model="InvoiceSeries",
        success_statuses=(201,),
    ),
    "retrieveInvoiceSeries": Operation(
        method="GET",
        path="/invoice-series/{id}",
        tag="Invoice series",
        request_model=None,
        response_model="InvoiceSeries",
        success_statuses=(200,),
    ),
    "updateInvoiceSeries": Operation(
        method="PATCH",
        path="/invoice-series/{id}",
        tag="Invoice series",
        request_model="InvoiceSeriesUpdate",
        response_model="InvoiceSeries",
        success_statuses=(200,),
    ),
    "deleteInvoiceSeries": Operation(
        method="DELETE",
        path="/invoice-series/{id}",
        tag="Invoice series",
        request_model=None,
        response_model=None,
        success_statuses=(204,),
    ),
    "listTaxRegimes": Operation(
        method="GET",
        path="/tax-regimes",
        tag="Tax regimes",
        request_model=None,
        response_model="TaxRegimeList",
        success_statuses=(200,),
    ),
    "retrieveTaxRegime": Operation(
        method="GET",
        path="/tax-regimes/{id}",
        tag="Tax regimes",
        request_model=None,
        response_model="TaxRegime",
        success_statuses=(200,),
    ),
    "retrieveTaxId": Operation(
        method="GET",
        path="/tax_ids/{id}",
        tag="Tax identifiers",
        request_model=None,
        response_model="TaxId",
        success_statuses=(200,),
    ),
    "listCustomers": Operation(
        method="GET",
        path="/customers",
        tag="Customers",
        request_model=None,
        response_model="CustomerList",
        success_statuses=(200,),
    ),
    "createCustomer": Operation(
        method="POST",
        path="/customers",
        tag="Customers",
        request_model="CustomerCreate",
        response_model="Customer",
        success_statuses=(201,),
    ),
    "retrieveCustomer": Operation(
        method="GET",
        path="/customers/{id}",
        tag="Customers",
        request_model=None,
        response_model="Customer",
        success_statuses=(200,),
    ),
    "updateCustomer": Operation(
        method="PATCH",
        path="/customers/{id}",
        tag="Customers",
        request_model="CustomerUpdate",
        response_model="Customer",
        success_statuses=(200,),
    ),
    "deleteCustomer": Operation(
        method="DELETE",
        path="/customers/{id}",
        tag="Customers",
        request_model=None,
        response_model=None,
        success_statuses=(204,),
    ),
    "listInvoices": Operation(
        method="GET",
        path="/invoices",
        tag="Invoices",
        request_model=None,
        response_model="InvoiceList",
        success_statuses=(200,),
    ),
    "issueInvoice": Operation(
        method="POST",
        path="/invoices",
        tag="Invoices",
        request_model="InvoiceCreate",
        response_model="Invoice",
        success_statuses=(201,),
    ),
    "retrieveInvoice": Operation(
        method="GET",
        path="/invoices/{id}",
        tag="Invoices",
        request_model=None,
        response_model="Invoice",
        success_statuses=(200,),
    ),
    "amendInvoice": Operation(
        method="POST",
        path="/invoices/{invoice_id}/amendments",
        tag="Invoices",
        request_model="InvoiceAmendmentCreate",
        response_model="InvoiceAmendment",
        success_statuses=(201,),
    ),
    "retrieveInvoicePdf": Operation(
        method="GET",
        path="/invoices/{invoice_id}/pdf",
        tag="Invoices",
        request_model=None,
        response_model="InvoicePdf",
        success_statuses=(200,),
    ),
    "renderInvoicePdf": Operation(
        method="POST",
        path="/invoices/{invoice_id}/pdf",
        tag="Invoices",
        request_model=None,
        response_model="InvoicePdf",
        success_statuses=(200, 201),
    ),
}
